{
    'name': "Mailchimp API Integration",
    'version': '12.1.0.0',
    'summary': """API Integration of Mailchimp with Odoo for mass mailing""",
    'description': """Integrate Mailchimp with Odoo and create Campaigns""",
    'author': "Planet odoo",
    'company': "Planet Odoo",
    'website': "http://www.planetodoo.com",
    "license": "AGPL-3",
    'category': 'Connector',
    'depends': ['base','mass_mailing'],
    "price": "333.00",
    "currency": "EUR",
    'data': [
        'security/ir.model.access.csv',
        'views/mass_mailing.xml',
        'views/mailchimp.xml',
    ],
    'external_dependencies': {'python': ['mailchimp3']},
    'qweb': [],
    'images': ['static/description/main.png'],
    'installable': True,
    'auto_install': False,
}